before:
  hooks:
    - go mod tidy
builds:
  - binary: sd-aws-consumer-service
    # Build for Linux and OSX
    goos:
      - linux
      - darwin
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
archives:
  - format: binary
    name_template: "{{.ProjectName}}_{{.Version}}_{{.Os}}-{{.Arch}}"
