builds:
  - binary: consumer-service
    # Build for Linux and OSX
    goos:
      - linux
      - darwin
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
    ldflags:
      - "-X github.com/screwdriver-cd/aws-consumer-service/cmd.version={{ .Version }}"
archives:
  - format: binary
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

