# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
builds:
  - binary: sd-aws-consumer-service
    # Build for Linux and OSX
    goos:
      - linux
      - darwin
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
archives:
  - format: binary
    name_template: "{{.ProjectName}}_{{.Version}}_{{.Os}}-{{.Arch}}"
  - replacements:
      darwin: Darwin
      linux: Linux
      386: i386
      amd64: x86_64
checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'
snapshot:
  name_template: "SNAPSHOT-{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
