shared:
    image: golang:1.19
    environment:
        GOPATH: /sd/workspace

jobs:
    main:
        environment:
            SD_SONAR_OPTS: "-Dsonar.sources=./ -Dsonar.exclusions=**/*_test.go,**/vendor/** -Dsonar.tests=./ -Dsonar.test.inclusions=**/*_test.go -Dsonar.test.exclusions=**/vendor/** -Dsonar.go.coverage.reportPaths=${SD_ARTIFACTS_DIR}/coverage.out -Dsonar.go.tests.reportPaths=${SD_ARTIFACTS_DIR}/report.json"
        requires: [~pr, ~commit]
        steps:
            - gover: go version
            - install: go mod download
            - vet: go vet ./...
            - tidy: go mod tidy
            - gofmt: (! gofmt -d -s . | grep '^')
            - test: make test JSONFILE=${SD_ARTIFACTS_DIR}/report.json COVERPROFILE=${SD_ARTIFACTS_DIR}/coverage.out
            - build: go build -tags lambda.norpc -a -o /dev/null
            - test-release: "curl -sL https://git.io/goreleaser | bash -s -- --snapshot"

    publish:
        requires: [main]
        steps:
            - setup-ci: git clone https://github.com/screwdriver-cd/toolbox.git $SD_ROOT_DIR/ci
            - get: go mod download
            - tag: $SD_ROOT_DIR/ci/git-tag.sh
            - clean: |
                [ -e VERSION ] && rm VERSION
            - release: "curl -sL https://git.io/goreleaser | bash"
        secrets:
            # Pushing tags to Git
            - GIT_KEY_BASE64
            # Pushing releases to GitHub
            - GITHUB_TOKEN
