shared:
    image: golang
    environment:
        GO111MODULE: on

jobs:
    main:
        image: golang:1.15.5
        environment:
            SD_SONAR_OPTS:  "-Dsonar.sources=./ -Dsonar.exclusions=**/*_test.go,**/vendor/** -Dsonar.tests=./ -Dsonar.test.inclusions=**/*_test.go -Dsonar.test.exclusions=**/vendor/** -Dsonar.go.coverage.reportPaths=${SD_ARTIFACTS_DIR}/coverage.out -Dsonar.go.tests.reportPaths=${SD_ARTIFACTS_DIR}/report.json"
        requires: [~commit, ~pr]
        steps:
            - gover: go version
            - install: go mod download
            - vet: go vet ./...
            - gofmt: (! gofmt -d . | grep '^')
            - test-setup: go get gotest.tools/gotestsum@v0.6.0
            - test: gotestsum --format testname --jsonfile ${SD_ARTIFACTS_DIR}/report.json -- -coverprofile=${SD_ARTIFACTS_DIR}/coverage.out ./...
            # Ensure we can compile
            - build: go build -a -o service
            - getreleaser: curl -sfL https://install.goreleaser.com/github.com/goreleaser/goreleaser.sh | sh
            # Test cross-compiling as well
            - test-release: ./bin/goreleaser release --snapshot
    publish:
        image: golang:1.15.5
        requires: main
        steps:
            - setup-ci: git clone https://github.com/screwdriver-cd/toolbox.git ci
            - get: go mod download
            - tag: ./ci/git-tag.sh
            - getreleaser: curl -sfL https://install.goreleaser.com/github.com/goreleaser/goreleaser.sh | sh
            - test-release: ./bin/goreleaser release
        secrets:
            # Pushing tags to Git
            - GIT_KEY
            # Pushing releases to GitHub
            - GITHUB_TOKEN
